---
- name: "Create an EKS cluster with build cache nodes"
  hosts: localhost
  connection: local
  roles:
    - eks-cache-cluster
    - eks-cache-cluster-shutdown
    - efs-mount
    - k8s-build-cache
