version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install -r operations/requirements.txt -q
      - aws secretsmanager get-secret-value --secret-id dev/ansible --query 'SecretString' --output text | jq -r '.vaultSecret' > ~/vault-pass
      - chmod +x gradlew
  build:
    commands:
      - printenv
      - ln -sf `which python3` /usr/bin/python # python link for ansible
      - ansible-playbook -i operations/inventories/dev/hosts operations/apps/deploy/app-deployment.yml --vault-password-file ~/vault-pass
  post_build:
    commands:
      - API_HOSTNAME=$(aws ssm get-parameter --name=/dev/API_HOSTNAME_"$BUILD" --query='Parameter.Value' --output text);
      - STATS_API_HOSTNAME=$(aws ssm get-parameter --name=/dev/STATS_API_HOSTNAME_"$BUILD" --query='Parameter.Value' --output text)
      - ./gradlew gatlingRun-ApiSimulation
      - ./gradlew gatlingRun-StatsApiSimulation
