version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - echo -e '#!/bin/bash\n  source operations/cicd/builds/roles/pipelines/files/scripts.sh; "$@"' > /bin/next
      - chmod +x gradlew
      - chmod +x /bin/next
      - source build_tag_source.sh
  build:
    commands:
      - printenv
      - next runGradle clean build -x test
  post_build:
    commands:
      - next runGradle test
      - next ifCI runGradle jib
reports:
  GradleCICDReportGroup:
    files:
      - "**/build/test-results/test/*.xml"
    discard-paths: no
    file-format: JunitXml