version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python3 -m pip install -r operations/requirements.txt
  build:
    commands:
      - printenv
      - ansible-playbook --version
      - which ansible-playbook
      - cat `which ansible-playbook` | head -n 5
      - cd operations
      - ansible-playbook -vvv -i inventories/dev/hosts apps/deploy/app-deployment.yml -e 'ansible_python_interpreter=/usr/bin/python3'
