version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install -r operations/requirements.txt
  build:
    commands:
      - ansible --version
      - cd operations
      - ansible-playbook -i inventories/dev/hosts apps/deploy/app-deployment.yml -e 'ansible_python_interpreter=/usr/bin/python3'
