version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - chmod +x gradlew
      - source operations/cicd/trigger/pr/roles/pipeline/files/scripts.sh
  build:
    commands:
      - printenv
      - next "clean build -x test"
  post_build:
    commands:
      - next "test"
      - ifCI next "jib"
reports:
  GradleCICDReportGroup:
    files:
      - "**/build/test-results/test/*.xml"
    discard-paths: no
    file-format: JunitXml