version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - chmod +x gradlew
      - export VAR=1
      - echo 'next() { source operations/cicd/trigger/pr/roles/pipeline/files/scripts.sh; "$@"; }' >> ~/.bashrc
  build:
    commands:
      - printenv
      - next runGradle clean build -x test
  post_build:
    commands:
      - next runGradle test
      - next ifCI runGradle jib
reports:
  GradleCICDReportGroup:
    files:
      - "**/build/test-results/test/*.xml"
    discard-paths: no
    file-format: JunitXml