version: 0.2
phases:
  build:
    commands:
      - printenv
      - SHA=$(cat .git/HEAD)
      - echo SHA = $SHA
      - PIPELINE_ID=$(aws codepipeline get-pipeline-state --name ${CODEBUILD_INITIATOR#codepipeline/} --query 'stageStates[?actionStates[?latestExecution.externalExecutionId==`'${CODEBUILD_BUILD_ID}'`]].latestExecution.pipelineExecutionId' --output text)
      - echo PIPELINE_ID = $PIPELINE_ID
      - BUILD_EXECUTION_ID=$(aws codepipeline list-action-executions --pipeline-name=Gradle-CICD-PR-Pipeline --filter="pipelineExecutionId=aaf48157-1e0b-42b6-be98-788af46bf3c8" --query 'actionExecutionDetails[?actionName==`Build`].output.executionResult.externalExecutionId' --output text)
      - echo BUILD_EXECUTION_ID = $BUILD_EXECUTION_ID
