version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - chmod +x gradlew
  build:
    commands:
      - printenv
      - ./gradlew --build-cache clean build -x test --info
  post_build:
    commands:
      - |
        if [[ $CODEBUILD_BUILD_SUCCEEDING = 1 ]]; then
          ./gradlew --build-cache test
        fi
reports:
  GradleCICDReportGroup:
    files:
      - '**/build/test-results/test/*.xml'
    discard-paths: no
    file-format: JunitXml