AWSTemplateFormatVersion: 2010-09-09
Description: "CodePipeline project for loading code from GitHub to S3 on PR"
Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
  CodePipelinePrPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-CodePipelinePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - logs:*
              - codebuild:*
            Resource: "*"
      Roles:
        - !Ref CodePipelineRole
Outputs:
  CodePipelineRoleARN:
    Description: "ARN of CodePipeline Role"
    Value: !GetAtt CodePipelineRole.Arn