- name: "Update EKS cache cluster config"
  shell: |
    aws eks --region "{{aws_region}}" update-kubeconfig --name "{{eks_cache_cluster_name}}"
- name: "Create a k8s namespace"
  k8s:
    name: "{{k8s_cache_cluster_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
- name: "Deploy EFS CSI driver"
  k8s:
    definition: "{{ lookup('template', 'efs-csi-driver.yml') }}"
- name: "Deploy build cache stack"
  k8s:
    definition: "{{ lookup('template', 'build-cache-stack.yml') }}"
    namespace: "{{k8s_cache_cluster_namespace}}"
- name: "Get the Cache Node load balancer URL"
  k8s_info:
    api_version: v1
    kind: Service
    name: "{{eks_cache_cluster_name}}-service"
    namespace: "{{k8s_cache_cluster_namespace}}"
  register: output
  until: output.resources[0].status.loadBalancer.ingress is defined
  retries: 10
  delay: 10
- name: "Register the Cache Node load balancer URL"
  set_fact:
    cache_node_url: "{{output.resources[0].status.loadBalancer.ingress[0].hostname}}"
- name: "Print the Cache Node load balancer URL"
  debug: msg="Load Balancer URL = {{ cache_node_url }}"