- name: "Establish contact with the EKS cluster"
  shell: "aws eks --region {{aws_region}} update-kubeconfig --name {{eks_cache_cluster_name}}"
- name: "Create a k8s namespace"
  k8s:
    name: "{{k8s_cache_cluster_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
- name: "Deploy build cache node"
  k8s:
    definition: "{{ lookup('template', 'build-cache-node.yml') }}"
