- name: "Update EKS app cluster config"
  shell: |
    aws eks --region "{{aws_region}}" update-kubeconfig --name "{{eks_app_cluster_name}}"
- name: "Create a k8s namespace"
  k8s:
    name: "{{k8s_app_cluster_namespace}}"
    api_version: v1
    kind: Namespace
    state: present
- name: "Deploy ConfigMaps and Secrets"
  k8s:
    definition: "{{ lookup('template', 'configMap-secret-stack.yml')}}"
    namespace: "{{k8s_app_cluster_namespace}}"
- name: "Clean up previous flyway definition"
  k8s:
    name: "{{eks_app_cluster_name}}-flyway-job"
    api_version: batch/v1
    kind: Job
    namespace: "{{k8s_app_cluster_namespace}}"
    state: absent
- name: "Run flyway"
  k8s:
    definition: "{{ lookup('template', 'flyway-job.yml')}}"
    namespace: "{{k8s_app_cluster_namespace}}"
  vars:
    build_tag: "$BUILD_TAG"
- name: "Deploy app stack"
  k8s:
    definition: "{{ lookup('template', 'deploy-app-stack.yml')}}"
    namespace: "{{k8s_app_cluster_namespace}}"
  vars:
    app_name: "{{item}}"
    build_tag: "$BUILD_TAG"
  with_items:
    - api
    - stats-api
    - stats-reporting
- name: "Get the Load balancer URL for API application"
  k8s_info:
    api_version: v1
    kind: Service
    name: "{{eks_app_cluster_name}}-api-service"
    namespace: "{{k8s_app_cluster_namespace}}"
  register: output_api
  until: output_api.resources[0].status.loadBalancer.ingress is defined
  retries: 10
  delay: 10
- name: "Get the Load balancer URL for Stats API application"
  k8s_info:
    api_version: v1
    kind: Service
    name: "{{eks_app_cluster_name}}-stats-api-service"
    namespace: "{{k8s_app_cluster_namespace}}"
  register: output_stats_api
  until: output_stats_api.resources[0].status.loadBalancer.ingress is defined
  retries: 10
  delay: 10
- name: "Register the load balancer URLs"
  set_fact:
    api_lb_url: "{{output_api.resources[0].status.loadBalancer.ingress[0].hostname}}"
    stats_api_lb_url: "{{output_stats_api.resources[0].status.loadBalancer.ingress[0].hostname}}"
- name: "Print the load balancer URLs"
  debug:
    msg:
      - "API Load Balancer URL = {{ api_lb_url }}"
      - "Stats API Load Balancer URL = {{ stats_api_lb_url }}"
- name : "Upload load balancer names to SSM"
  shell: |
    aws ssm put-parameter --name "{{api_lb_url_prefix}}_${BUILD:-LOCAL}" --type String --value "{{api_lb_url}}" --overwrite
    aws ssm put-parameter --name "{{stats_api_lb_url_prefix}}_${BUILD:-LOCAL}" --type String --value "{{stats_api_lb_url}}" --overwrite