- name: Create a Codepipeline role
  cloudformation:
    stack_name: "CodePipeline-role"
    state: "present"
    region: "{{aws_region}}"
    template_body: "{{lookup('template', 'pr-codepipeline-role-template.yml')}}"
  register: output
- name: Register role ARN
  set_fact:
    codepipeline_role_arn: "{{output.stack_outputs.CodePipelineRoleARN}}"
- name: Output role ARN
  debug: msg="CodePipeline role ARN = {{ codepipeline_role_arn }}"