- name: "Insert secure parameters into parameter store"
  shell: |
    aws ssm delete-parameter --name "{{github_token_ssm_parameter}}"
    aws ssm put-parameter --name "{{github_token_ssm_parameter}}" --type "SecureString" --value "{{github_token}}"