AWSTemplateFormatVersion: 2010-09-09
Description: "CodeBuild project for loading code from GitHub to S3 on PR"
Resources:
  CodeBuildPr:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        ArtifactIdentifier: "Sources for PR builds"
        EncryptionDisabled: false
        Packaging: NONE
        Location: !Ref S3OutputBucket
        Name: "/"
        Type: S3
      Description: "PR trigger CodeBuild"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
      Name: "{{project_name}}-{{codebuild_projectname_trigger}}"
      ServiceRole: "{{codebuild_role_arn}}"
      Source:
        ReportBuildStatus: true
        BuildStatusConfig:
          Context: pr-trigger
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - zip -r {{source_artifact_key}} .
          artifacts:
            files:
              - {{source_artifact_key}}
        Type: GITHUB
        Location: https://github.com/romanastr/base-gradle-cicd
      Triggers:
        FilterGroups:
          -
            - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED
        Webhook: true
      LogsConfig:
        CloudWatchLogs:
          GroupName: "/aws/codebuild/{{project_name}}-{{codebuild_projectname_trigger}}"
          Status: ENABLED
  S3OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "{{source_artifact_bucket_name}}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionRule
            Status: Enabled
            ExpirationInDays: "{{audit_expiration_days}}"
            Transitions:
              - TransitionInDays: "{{audit_infrequent_transition_days}}"
                StorageClass: STANDARD_IA
          - Id: NoncurrentVersionTransitionRule
            Status: Enabled
            NoncurrentVersionExpirationInDays: "{{audit_expiration_days}}"
            NoncurrentVersionTransitions:
              - TransitionInDays: "{{audit_infrequent_transition_days}}"
                StorageClass: STANDARD_IA
      VersioningConfiguration:
        Status: Enabled
  LogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/codebuild/{{project_name}}-{{codebuild_projectname_trigger}}"
      RetentionInDays: "{{audit_expiration_days}}"