AWSTemplateFormatVersion: 2010-09-09
Description: "CodePipeline project"
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "{{project_name}}-PR-Pipeline"
      RoleArn: "{{codepipeline_role_arn}}"
      Stages:
        -
          Name: Source
          Actions:
            - Name: S3SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                S3Bucket: "{{source_artifact_bucket_name}}"
                S3ObjectKey: "{{source_artifact_key}}"
              RunOrder: 1
        -
          Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
            - Name: BuildStatus
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuildStatus
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStoreBucket
  CodePipelineArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionRule
            Status: Enabled
            ExpirationInDays: "{{audit_expiration_days}}"
            Transitions:
              - TransitionInDays: "{{audit_infrequent_transition_days}}"
                StorageClass: STANDARD_IA
  CodeBuildBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: "Main Build for PRs"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: BUILD_CACHE_HOST
            Value: "{{cache_node_host_ssm_parameter}}"
            Type: PARAMETER_STORE
          - Name: CI
            Value: true
            Type: PLAINTEXT
      Name: "{{project_name}}-{{codebuild_projectname_main}}"
      ServiceRole: "{{codebuild_role_arn}}"
      Source:
        Type: CODEPIPELINE
        BuildSpec: operations/cicd/trigger/pr/roles/pipeline/files/buildspec-build.yml
      LogsConfig:
        CloudWatchLogs:
          GroupName: "/aws/codebuild/{{project_name}}-{{codebuild_projectname_main}}"
          Status: ENABLED
  LogsLogGroupMain:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/codebuild/{{project_name}}-{{codebuild_projectname_main}}"
      RetentionInDays: "{{audit_expiration_days}}"
  CodeBuildStatus:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: "Reporting Build status for PRs"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Value: "{{github_token_ssm_parameter}}"
            Type: PARAMETER_STORE
      Name: "{{project_name}}-{{codebuild_projectname_status}}"
      ServiceRole: "{{codebuild_role_arn}}"
      Source:
        Type: CODEPIPELINE
        BuildSpec: operations/cicd/trigger/pr/roles/pipeline/files/buildspec-build-status.yml
      LogsConfig:
        CloudWatchLogs:
          GroupName: "/aws/codebuild/{{project_name}}-{{codebuild_projectname_status}}"
          Status: ENABLED
  LogsLogGroupStatus:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/codebuild/{{project_name}}-{{codebuild_projectname_status}}"
      RetentionInDays: "{{audit_expiration_days}}"