apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{eks_app_cluster_name}}-config-map"
data:
  SPRING_DATASOURCE_URL: "jdbc:mariadb://{{app_db_connection_url}}:{{app_db_port}}/{{app_db_database}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{eks_app_cluster_name}}-secret"
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "{{ app_db_username | b64encode }}"
  SPRING_DATASOURCE_PASSWORD: "{{ app_db_password | b64encode }}"
