apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{eks_app_cluster_name}}-config-map"
data:
  SPRING_DATASOURCE_URL: "jdbc:mariadb://{{app_db_connection_url}}:{{app_db_port}}/{{app_db_database}}"
  SPRING_ACTIVEMQ_BROKER_URL: "{{amazon_mq_connection_url}}"
  REPORTING_PROTOCOL: "jms"
  REPORTING_QUEUE_NAME: "{{message_bus_queue_name}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{eks_app_cluster_name}}-secret"
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "{{ app_db_username | b64encode }}"
  SPRING_DATASOURCE_PASSWORD: "{{ app_db_password | b64encode }}"
  SPRING_ACTIVEMQ_USER: "{{ message_bus_username | b64encode }}"
  SPRING_ACTIVEMQ_PASSWORD: "{{ message_bus_password | b64encode }}"
