apiVersion: v1
kind: Service
metadata:
  name: "{{eks_app_cluster_name}}-{{app_name}}-service"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: "{{k8s_app_cluster_namespace}}-{{app_name}}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{app_name}}"
  labels:
    app: "{{k8s_app_cluster_namespace}}-{{app_name}}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{k8s_app_cluster_namespace}}-{{app_name}}"
  template:
    metadata:
      labels:
        app: "{{k8s_app_cluster_namespace}}-{{app_name}}"
    spec:
      containers:
        - name: "{{app_name}}"
          image: "{{aws_account_id}}.dkr.ecr.us-east-1.amazonaws.com/base-gradle-{{app_name}}:{{k8s_app_version}}"
          ports:
            - containerPort: 8080