- name: "Create EKS cluster for CI/CD"
  cloudformation:
    stack_name: "{{eks_cache_cluster_stack_name}}"
    state: "present"
    region: "{{aws_region}}"
    template_body: "{{lookup('template', 'eks-cache-cluster.yml')}}"