- name: "Create EKS cluster for CI/CD"
  cloudformation:
    stack_name: "{{eks_cache_cluster_stack_name}}"
    state: present
    region: "{{aws_region}}"
    template_body: "{{lookup('template', '{{shared_folder}}/eks-cluster.yml')}}"
    template_parameters:
      ClusterName: "{{eks_cache_cluster_name}}"
      CidrBlock: "{{eks_cache_cluster_cidr_block}}"
      AvailabilityZone1: "{{eks_cache_cluster_az_1}}"
      AvailabilityZone2: "{{eks_cache_cluster_az_2}}"
      KubernetesVersion: "{{eks_cluster_kubernetes_version}}"
  register: output
- name: "Register VPC id"
  set_fact:
    eks_cache_cluster_vpc_id: "{{output.stack_outputs.VPC}}"
- name: "Print VPC id"
  debug: msg="EKS cache cluster VPC id = {{ eks_cache_cluster_vpc_id }}"
- name: "Enable EKS cluster Cloudwatch logging"
  shell: |
    aws eks --region "{{aws_region}}" update-cluster-config --name "{{eks_cache_cluster_name}}" \
      --logging '{"clusterLogging":[{"types":["api","audit","authenticator","controllerManager","scheduler"],"enabled":true}]}'
    aws logs put-retention-policy --log-group-name "/aws/eks/{{eks_cache_cluster_name}}/cluster" \
      --retention-in-days "{{audit_expiration_days}}"